### ISSUE TITLE
Not selecting location from auto-complete list causes internal server error

### ISSUE THREAD

**Issue by jillh510** [iandees/carpools#48] opened 2017-04-18 22:45 UTC
Steps to reproduce:
- Go to "Add a Carpool" page
- Type some nonsense for the "Leaving from" or "Going to" field. Don't pick an entry from the dropdown.
- Add the carpool

Result: Internal server error

**Comment by iandees** [comment] 2017-04-18 23:52
Dupe of https://github.com/iandees/carpools/issues/43.

**Closed by iandees** 2017-04-18 23:52 UTC
Labels: bug
